source 'https://rubygems.org'

group :development do
  gem 'vagrant', git: 'https://github.com/mitchellh/vagrant.git'
  gem 'rubocop', require: false
end

group :plugins do
  gem 'vagrant-rancher-provisioner', path: '.'
end
